# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/xiaomi/aries/setup-makefiles.sh

#bin
PRODUCT_COPY_FILES += \
    vendor/xiaomi/aries/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    vendor/xiaomi/aries/proprietary/bin/brctl:system/bin/brctl \
    vendor/xiaomi/aries/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/xiaomi/aries/proprietary/bin/cnd:system/bin/cnd \
    vendor/xiaomi/aries/proprietary/bin/diag_callback_client:system/bin/diag_callback_client \
    vendor/xiaomi/aries/proprietary/bin/diag_klog:system/bin/diag_klog \
    vendor/xiaomi/aries/proprietary/bin/diag_mdlog:system/bin/diag_mdlog \
    vendor/xiaomi/aries/proprietary/bin/diag_socket_log:system/bin/diag_socket_log \
    vendor/xiaomi/aries/proprietary/bin/diag_uart_log:system/bin/diag_uart_log \
    vendor/xiaomi/aries/proprietary/bin/dpmd:system/bin/dpmd \
    vendor/xiaomi/aries/proprietary/bin/drmdiagapp:system/bin/drmdiagapp \
    vendor/xiaomi/aries/proprietary/bin/dumpe2fs:system/bin/dumpe2fs \
    vendor/xiaomi/aries/proprietary/bin/dun-server:system/bin/dun-server \
    vendor/xiaomi/aries/proprietary/bin/ebtables:system/bin/ebtables \
    vendor/xiaomi/aries/proprietary/bin/efsks:system/bin/efsks \
    vendor/xiaomi/aries/proprietary/bin/fdpp:system/bin/fdpp \
    vendor/xiaomi/aries/proprietary/bin/fmconfig:system/bin/fmconfig \
    vendor/xiaomi/aries/proprietary/bin/fmfactorytest:system/bin/fmfactorytest \
    vendor/xiaomi/aries/proprietary/bin/fmfactorytestserver:system/bin/fmfactorytestserver \
    vendor/xiaomi/aries/proprietary/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
    vendor/xiaomi/aries/proprietary/bin/ftmdaemon:system/bin/ftmdaemon \
    vendor/xiaomi/aries/proprietary/bin/garden_app:system/bin/garden_app \
    vendor/xiaomi/aries/proprietary/bin/gpsone_daemon:system/bin/gpsone_daemon \
    vendor/xiaomi/aries/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/xiaomi/aries/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/xiaomi/aries/proprietary/bin/isdbtmmtest:system/bin/isdbtmmtest \
    vendor/xiaomi/aries/proprietary/bin/ks:system/bin/ks \
    vendor/xiaomi/aries/proprietary/bin/location-mq:system/bin/location-mq \
    vendor/xiaomi/aries/proprietary/bin/loc_launcher:system/bin/loc_launcher \
    vendor/xiaomi/aries/proprietary/bin/lowi-server:system/bin/lowi-server \
    vendor/xiaomi/aries/proprietary/bin/lowi_test:system/bin/lowi_test \
    vendor/xiaomi/aries/proprietary/bin/mcd:system/bin/mcd \
    vendor/xiaomi/aries/proprietary/bin/mcStarter:system/bin/mcStarter \
    vendor/xiaomi/aries/proprietary/bin/mdm_helper:system/bin/mdm_helper \
    vendor/xiaomi/aries/proprietary/bin/minizip:system/bin/minizip \
    vendor/xiaomi/aries/proprietary/bin/mm-jpeg-dec-test:system/bin/mm-jpeg-dec-test \
    vendor/xiaomi/aries/proprietary/bin/mm-jpeg-dec-test-client:system/bin/mm-jpeg-dec-test-client \
    vendor/xiaomi/aries/proprietary/bin/mm-jpeg-enc-test:system/bin/mm-jpeg-enc-test \
    vendor/xiaomi/aries/proprietary/bin/mm-jpeg-enc-test-client:system/bin/mm-jpeg-enc-test-client \
    vendor/xiaomi/aries/proprietary/bin/mm-jps-enc-test:system/bin/mm-jps-enc-test \
    vendor/xiaomi/aries/proprietary/bin/mm-mpo-dec-test:system/bin/mm-mpo-dec-test \
    vendor/xiaomi/aries/proprietary/bin/mm-mpo-enc-test:system/bin/mm-mpo-enc-test \
    vendor/xiaomi/aries/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    vendor/xiaomi/aries/proprietary/bin/mm-qcamera-app:system/bin/mm-qcamera-app \
    vendor/xiaomi/aries/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/xiaomi/aries/proprietary/bin/mm-qcamera-test:system/bin/mm-qcamera-test \
    vendor/xiaomi/aries/proprietary/bin/mm-qcamera-testsuite-client:system/bin/mm-qcamera-testsuite-client \
    vendor/xiaomi/aries/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/xiaomi/aries/proprietary/bin/namespaceCreateSvc:system/bin/namespaceCreateSvc \
    vendor/xiaomi/aries/proprietary/bin/namespaceInit:system/bin/namespaceInit \
    vendor/xiaomi/aries/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/xiaomi/aries/proprietary/bin/nl_listener:system/bin/nl_listener \
    vendor/xiaomi/aries/proprietary/bin/n_smux:system/bin/n_smux \
    vendor/xiaomi/aries/proprietary/bin/oemwvtest:system/bin/oemwvtest \
    vendor/xiaomi/aries/proprietary/bin/perfd:system/bin/perfd \
    vendor/xiaomi/aries/proprietary/bin/PktRspTest:system/bin/PktRspTest \
    vendor/xiaomi/aries/proprietary/bin/profiler_daemon:system/bin/profiler_daemon \
    vendor/xiaomi/aries/proprietary/bin/ptt_socket_app:system/bin/ptt_socket_app \
    vendor/xiaomi/aries/proprietary/bin/qcks:system/bin/qcks \
    vendor/xiaomi/aries/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/xiaomi/aries/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/xiaomi/aries/proprietary/bin/qseecom_sample_client:system/bin/qseecom_sample_client \
    vendor/xiaomi/aries/proprietary/bin/qseecom_security_test:system/bin/qseecom_security_test \
    vendor/xiaomi/aries/proprietary/bin/quipc_igsn:system/bin/quipc_igsn \
    vendor/xiaomi/aries/proprietary/bin/quipc_main:system/bin/quipc_main \
    vendor/xiaomi/aries/proprietary/bin/radish:system/bin/radish \
    vendor/xiaomi/aries/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/xiaomi/aries/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/xiaomi/aries/proprietary/bin/ssr_diag:system/bin/ssr_diag \
    vendor/xiaomi/aries/proprietary/bin/StoreKeybox:system/bin/StoreKeybox \
    vendor/xiaomi/aries/proprietary/bin/subsystem_ramdump:system/bin/subsystem_ramdump \
    vendor/xiaomi/aries/proprietary/bin/test_diag:system/bin/test_diag \
    vendor/xiaomi/aries/proprietary/bin/test_gemini:system/bin/test_gemini \
    vendor/xiaomi/aries/proprietary/bin/thermald:system/bin/thermald \
    vendor/xiaomi/aries/proprietary/bin/thermal-engine:system/bin/thermal-engine \
    vendor/xiaomi/aries/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/xiaomi/aries/proprietary/bin/usbhub:system/bin/usbhub \
    vendor/xiaomi/aries/proprietary/bin/usbhub_init:system/bin/usbhub_init \
    vendor/xiaomi/aries/proprietary/bin/usf_epos:system/bin/usf_epos \
    vendor/xiaomi/aries/proprietary/bin/usf_tester:system/bin/usf_tester \
    vendor/xiaomi/aries/proprietary/bin/v4l2-qcamera-app:system/bin/v4l2-qcamera-app \
    vendor/xiaomi/aries/proprietary/bin/vpcmd:system/bin/vpcmd \
    vendor/xiaomi/aries/proprietary/bin/wdsdaemon:system/bin/wdsdaemon \
    vendor/xiaomi/aries/proprietary/bin/xtwifi-client:system/bin/xtwifi-client \
    vendor/xiaomi/aries/proprietary/bin/xtwifi-inet-agent:system/bin/xtwifi-inet-agent \
    vendor/xiaomi/aries/proprietary/bin/zip_utils:system/bin/zip_utils \

#etc/firmware
PRODUCT_COPY_FILES += \
    vendor/xiaomi/aries/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/xiaomi/aries/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/xiaomi/aries/proprietary/etc/firmware/cyttsp_8064_mtp.hex:system/etc/firmware/cyttsp_8064_mtp.hex \
    vendor/xiaomi/aries/proprietary/etc/firmware/cyttsp_8960_cdp.hex:system/etc/firmware/cyttsp_8960_cdp.hex \
    vendor/xiaomi/aries/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/xiaomi/aries/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/xiaomi/aries/proprietary/etc/firmware/vidc.b00:system/etc/firmware/vidc.b00 \
    vendor/xiaomi/aries/proprietary/etc/firmware/vidc.b01:system/etc/firmware/vidc.b01 \
    vendor/xiaomi/aries/proprietary/etc/firmware/vidc.b02:system/etc/firmware/vidc.b02 \
    vendor/xiaomi/aries/proprietary/etc/firmware/vidc.b03:system/etc/firmware/vidc.b03 \
    vendor/xiaomi/aries/proprietary/etc/firmware/vidc.mdt:system/etc/firmware/vidc.mdt \
    vendor/xiaomi/aries/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/xiaomi/aries/proprietary/etc/firmware/vidcfw.elf:system/etc/firmware/vidcfw.elf \
    vendor/xiaomi/aries/proprietary/etc/firmware/voiceproc.img:system/etc/firmware/voiceproc.img \
    vendor/xiaomi/aries/proprietary/etc/firmware/voiceproc_init.img:system/etc/firmware/voiceproc_init.img \

#lib/drm
PRODUCT_COPY_FILES += \
    vendor/xiaomi/aries/proprietary/lib/drm/libdrmprplugin.so:system/lib/drm/libdrmprplugin.so \

#lib/hw
PRODUCT_COPY_FILES += \
    vendor/xiaomi/aries/proprietary/lib/hw/camera.msm8960.so:system/lib/hw/camera.vendor.msm8960.so \
    vendor/xiaomi/aries/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/xiaomi/aries/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \

#other libs
PRODUCT_COPY_FILES += \
    vendor/xiaomi/aries/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/xiaomi/aries/proprietary/lib/libACRCloudEngine.so:system/lib/libACRCloudEngine.so \
    vendor/xiaomi/aries/proprietary/lib/libadsprpc.so:system/lib/libadsprpc.so \
    vendor/xiaomi/aries/proprietary/lib/libadvanced_crypto.so:system/lib/libadvanced_crypto.so \
    vendor/xiaomi/aries/proprietary/lib/libadvanced_crypto_jni.so:system/lib/libadvanced_crypto_jni.so \
    vendor/xiaomi/aries/proprietary/lib/libairtunes.so:system/lib/libairtunes.so \
    vendor/xiaomi/aries/proprietary/lib/libairtunes_jni.so:system/lib/libairtunes_jni.so \
    vendor/xiaomi/aries/proprietary/lib/libAKM.so:system/lib/libAKM.so \
    vendor/xiaomi/aries/proprietary/lib/libalsautils.so:system/lib/libalsautils.so \
    vendor/xiaomi/aries/proprietary/lib/libams-1.1.7-mfr.so:system/lib/libams-1.1.7-mfr.so \
    vendor/xiaomi/aries/proprietary/lib/libams-1.1.7-m-mfr.so:system/lib/libams-1.1.7-m-mfr.so \
    vendor/xiaomi/aries/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/xiaomi/aries/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/xiaomi/aries/proprietary/lib/libavast-utils.so:system/lib/libavast-utils.so \
    vendor/xiaomi/aries/proprietary/lib/libavast-vps-interface.so:system/lib/libavast-vps-interface.so \
    vendor/xiaomi/aries/proprietary/lib/libavresample.so:system/lib/libavresample.so \
    vendor/xiaomi/aries/proprietary/lib/libbson.so:system/lib/libbson.so \
    vendor/xiaomi/aries/proprietary/lib/libCameraEffectJNI.so:system/lib/libCameraEffectJNI.so \
    vendor/xiaomi/aries/proprietary/lib/libcdc.so:system/lib/libcdc.so \

#cromatix libs
PRODUCT_COPY_FILES += \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_imx074_video_hd.so:system/lib/libchromatix_imx074_video_hd.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_imx091_default_video.so:system/lib/libchromatix_imx091_default_video.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_imx091_preview.so:system/lib/libchromatix_imx091_preview.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_imx091_video_hd.so:system/lib/libchromatix_imx091_video_hd.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_imx132_default_video.so:system/lib/libchromatix_imx132_default_video.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_imx132_preview.so:system/lib/libchromatix_imx132_preview.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_imx132_zsl.so:system/lib/libchromatix_imx132_zsl.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_imx135_default_video.so:system/lib/libchromatix_imx135_default_video.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_imx135_preview.so:system/lib/libchromatix_imx135_preview.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_imx135_video_hd.so:system/lib/libchromatix_imx135_video_hd.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_imx135_video_hdr.so:system/lib/libchromatix_imx135_video_hdr.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_imx135_zsl.so:system/lib/libchromatix_imx135_zsl.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_imx175_default_video.so:system/lib/libchromatix_imx175_default_video.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_imx175_preview.so:system/lib/libchromatix_imx175_preview.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_imx175_zsl.so:system/lib/libchromatix_imx175_zsl.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_mt9e013_default_video.so:system/lib/libchromatix_mt9e013_default_video.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_mt9e013_preview.so:system/lib/libchromatix_mt9e013_preview.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_mt9e013_video_hfr.so:system/lib/libchromatix_mt9e013_video_hfr.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_ov2720_hfr.so:system/lib/libchromatix_ov2720_hfr.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_ov2720_zsl.so:system/lib/libchromatix_ov2720_zsl.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_ov5647_default_video.so:system/lib/libchromatix_ov5647_default_video.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_ov5647_preview.so:system/lib/libchromatix_ov5647_preview.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_ov8825_default_video.so:system/lib/libchromatix_ov8825_default_video.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_ov8825_preview.so:system/lib/libchromatix_ov8825_preview.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_ov8825_video_hfr.so:system/lib/libchromatix_ov8825_video_hfr.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_ov8825_video_hfr_60fps.so:system/lib/libchromatix_ov8825_video_hfr_60fps.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_ov8825_video_hfr_90fps.so:system/lib/libchromatix_ov8825_video_hfr_90fps.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_ov8825_video_hfr_120fps.so:system/lib/libchromatix_ov8825_video_hfr_120fps.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_ov8825_zsl.so:system/lib/libchromatix_ov8825_zsl.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_ov9726_default_video.so:system/lib/libchromatix_ov9726_default_video.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_ov9726_preview.so:system/lib/libchromatix_ov9726_preview.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_s5k3h7_default_video.so:system/lib/libchromatix_s5k3h7_default_video.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_s5k3h7_preview.so:system/lib/libchromatix_s5k3h7_preview.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_s5k3h7_zsl.so:system/lib/libchromatix_s5k3h7_zsl.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_s5k3l1yx_default_video.so:system/lib/libchromatix_s5k3l1yx_default_video.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_s5k3l1yx_preview.so:system/lib/libchromatix_s5k3l1yx_preview.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_s5k3l1yx_video_hd.so:system/lib/libchromatix_s5k3l1yx_video_hd.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_s5k3l1yx_zsl.so:system/lib/libchromatix_s5k3l1yx_zsl.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
    vendor/xiaomi/aries/proprietary/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \

#other libs
PRODUCT_COPY_FILES += \
    vendor/xiaomi/aries/proprietary/lib/libCommandSvc.so:system/lib/libCommandSvc.so \
    vendor/xiaomi/aries/proprietary/lib/libcsd-client.so:system/lib/libcsd-client.so \
    vendor/xiaomi/aries/proprietary/lib/libdatabase_sqlcipher-ss40103.so:system/lib/libdatabase_sqlcipher-ss40103.so \
    vendor/xiaomi/aries/proprietary/lib/libdce-1.1.6-mfr.so:system/lib/libdce-1.1.6-mfr.so \
    vendor/xiaomi/aries/proprietary/lib/libdce-1.1.9-mfr.so:system/lib/libdce-1.1.9-mfr.so \
    vendor/xiaomi/aries/proprietary/lib/libDexHelper.so:system/lib/libDexHelper.so \
    vendor/xiaomi/aries/proprietary/lib/libdidi_secure.so:system/lib/libdidi_secure.so \
    vendor/xiaomi/aries/proprietary/lib/libdigit_ocr.so:system/lib/libdigit_ocr.so \
    vendor/xiaomi/aries/proprietary/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
    vendor/xiaomi/aries/proprietary/lib/libdrmdiag.so:system/lib/libdrmdiag.so \
    vendor/xiaomi/aries/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
    vendor/xiaomi/aries/proprietary/lib/libdrmtime.so:system/lib/libdrmtime.so \
    vendor/xiaomi/aries/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/xiaomi/aries/proprietary/lib/libdsprofile.so:system/lib/libdsprofile.so \
    vendor/xiaomi/aries/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/xiaomi/aries/proprietary/lib/libdsucsd.so:system/lib/libdsucsd.so \
    vendor/xiaomi/aries/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/xiaomi/aries/proprietary/lib/libduokantext.so:system/lib/libduokantext.so \
    vendor/xiaomi/aries/proprietary/lib/libebt_802_3.so:system/lib/libebt_802_3.so \
    vendor/xiaomi/aries/proprietary/lib/libebtable_broute.so:system/lib/libebtable_broute.so \
    vendor/xiaomi/aries/proprietary/lib/libebtable_filter.so:system/lib/libebtable_filter.so \
    vendor/xiaomi/aries/proprietary/lib/libebtable_nat.so:system/lib/libebtable_nat.so \
    vendor/xiaomi/aries/proprietary/lib/libebt_among.so:system/lib/libebt_among.so \
    vendor/xiaomi/aries/proprietary/lib/libebt_arp.so:system/lib/libebt_arp.so \
    vendor/xiaomi/aries/proprietary/lib/libebt_arpreply.so:system/lib/libebt_arpreply.so \
    vendor/xiaomi/aries/proprietary/lib/libebtc.so:system/lib/libebtc.so \
    vendor/xiaomi/aries/proprietary/lib/libebt_ip.so:system/lib/libebt_ip.so \
    vendor/xiaomi/aries/proprietary/lib/libebt_ip6.so:system/lib/libebt_ip6.so \
    vendor/xiaomi/aries/proprietary/lib/libebt_limit.so:system/lib/libebt_limit.so \
    vendor/xiaomi/aries/proprietary/lib/libebt_log.so:system/lib/libebt_log.so \
    vendor/xiaomi/aries/proprietary/lib/libebt_mark.so:system/lib/libebt_mark.so \
    vendor/xiaomi/aries/proprietary/lib/libebt_mark_m.so:system/lib/libebt_mark_m.so \
    vendor/xiaomi/aries/proprietary/lib/libebt_nat.so:system/lib/libebt_nat.so \
    vendor/xiaomi/aries/proprietary/lib/libebt_nflog.so:system/lib/libebt_nflog.so \
    vendor/xiaomi/aries/proprietary/lib/libebt_pkttype.so:system/lib/libebt_pkttype.so \
    vendor/xiaomi/aries/proprietary/lib/libebt_redirect.so:system/lib/libebt_redirect.so \
    vendor/xiaomi/aries/proprietary/lib/libebt_standard.so:system/lib/libebt_standard.so \
    vendor/xiaomi/aries/proprietary/lib/libebt_stp.so:system/lib/libebt_stp.so \
    vendor/xiaomi/aries/proprietary/lib/libebt_ulog.so:system/lib/libebt_ulog.so \
    vendor/xiaomi/aries/proprietary/lib/libebt_vlan.so:system/lib/libebt_vlan.so \
    vendor/xiaomi/aries/proprietary/lib/libExtendedExtractor.so:system/lib/libExtendedExtractor.so \
    vendor/xiaomi/aries/proprietary/lib/libextendedremotedisplay.so:system/lib/libextendedremotedisplay.so \
    vendor/xiaomi/aries/proprietary/lib/libfamily_jni.so:system/lib/libfamily_jni.so \
    vendor/xiaomi/aries/proprietary/lib/libfdpp.so:system/lib/libfdpp.so \
    vendor/xiaomi/aries/proprietary/lib/libfdpp_jni.so:system/lib/libfdpp_jni.so \
    vendor/xiaomi/aries/proprietary/lib/libffmpeg-miplayer.so:system/lib/libffmpeg-miplayer.so \
    vendor/xiaomi/aries/proprietary/lib/libffmpeg_xm.so:system/lib/libffmpeg_xm.so \
    vendor/xiaomi/aries/proprietary/lib/libFileMux.so:system/lib/libFileMux.so \
    vendor/xiaomi/aries/proprietary/lib/libfilterpack_facedetect.so:system/lib/libfilterpack_facedetect.so \
    vendor/xiaomi/aries/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/xiaomi/aries/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/xiaomi/aries/proprietary/lib/libhttpserver.so:system/lib/libhttpserver.so \
    vendor/xiaomi/aries/proprietary/lib/libhw_instanttrans.so:system/lib/libhw_instanttrans.so \
    vendor/xiaomi/aries/proprietary/lib/libhwocr_cntools_shared.so:system/lib/libhwocr_cntools_shared.so \
    vendor/xiaomi/aries/proprietary/lib/libI420colorconvert.so:system/lib/libI420colorconvert.so \
    vendor/xiaomi/aries/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/xiaomi/aries/proprietary/lib/libimage-jpeg-dec-omx-comp.so:system/lib/libimage-jpeg-dec-omx-comp.so \
    vendor/xiaomi/aries/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/xiaomi/aries/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/xiaomi/aries/proprietary/lib/libImageSearchAPI.so:system/lib/libImageSearchAPI.so \
    vendor/xiaomi/aries/proprietary/lib/libjavastackimpl.so:system/lib/libjavastackimpl.so \
    vendor/xiaomi/aries/proprietary/lib/libJeejenAisound.so:system/lib/libJeejenAisound.so \
    vendor/xiaomi/aries/proprietary/lib/libjeejenmsc.so:system/lib/libjeejenmsc.so \
    vendor/xiaomi/aries/proprietary/lib/libjni_load_serinum.so:system/lib/libjni_load_serinum.so \
    vendor/xiaomi/aries/proprietary/lib/libjni_resource_drm.so:system/lib/libjni_resource_drm.so \
    vendor/xiaomi/aries/proprietary/lib/libkcmutil.so:system/lib/libkcmutil.so \
    vendor/xiaomi/aries/proprietary/lib/libkeygen_jni.so:system/lib/libkeygen_jni.so \
    vendor/xiaomi/aries/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/xiaomi/aries/proprietary/lib/libloc_core.so:system/lib/libloc_core.so \
    vendor/xiaomi/aries/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    vendor/xiaomi/aries/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/xiaomi/aries/proprietary/lib/libmercury.so:system/lib/libmercury.so \
    vendor/xiaomi/aries/proprietary/lib/libmiio.so:system/lib/libmiio.so \
    vendor/xiaomi/aries/proprietary/lib/libmiomxinterface.so:system/lib/libmiomxinterface.so \
    vendor/xiaomi/aries/proprietary/lib/libmm-abl.so:system/lib/libmm-abl.so \
    vendor/xiaomi/aries/proprietary/lib/libmm-abl-oem.so:system/lib/libmm-abl-oem.so \
    vendor/xiaomi/aries/proprietary/lib/libmm-audio-resampler.so:system/lib/libmm-audio-resampler.so \

PRODUCT_COPY_FILES += \
    vendor/xiaomi/aries/proprietary/lib/libmmcamera_3a_legacy.so:system/lib/libmmcamera_3a_legacy.so \
    vendor/xiaomi/aries/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/xiaomi/aries/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/xiaomi/aries/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/xiaomi/aries/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/xiaomi/aries/proprietary/lib/libmmcamera_imx091.so:system/lib/libmmcamera_imx091.so \
    vendor/xiaomi/aries/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/xiaomi/aries/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
    vendor/xiaomi/aries/proprietary/lib/libmmcamera_plugin.so:system/lib/libmmcamera_plugin.so \
    vendor/xiaomi/aries/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
    vendor/xiaomi/aries/proprietary/lib/libmmcamera_tintless_algo.so:system/lib/libmmcamera_tintless_algo.so \
    vendor/xiaomi/aries/proprietary/lib/libmmcamera_tintless_wrapper.so:system/lib/libmmcamera_tintless_wrapper.so \
    vendor/xiaomi/aries/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/xiaomi/aries/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/xiaomi/aries/proprietary/lib/libmmhttpstack.so:system/lib/libmmhttpstack.so \
    vendor/xiaomi/aries/proprietary/lib/libmmiipstreammmihttp.so:system/lib/libmmiipstreammmihttp.so \
    vendor/xiaomi/aries/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/xiaomi/aries/proprietary/lib/libmmipstreamaal.so:system/lib/libmmipstreamaal.so \
    vendor/xiaomi/aries/proprietary/lib/libmmipstreamnetwork.so:system/lib/libmmipstreamnetwork.so \
    vendor/xiaomi/aries/proprietary/lib/libmmipstreamsourcehttp.so:system/lib/libmmipstreamsourcehttp.so \
    vendor/xiaomi/aries/proprietary/lib/libmmipstreamutils.so:system/lib/libmmipstreamutils.so \
    vendor/xiaomi/aries/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/xiaomi/aries/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/xiaomi/aries/proprietary/lib/libmmjps.so:system/lib/libmmjps.so \
    vendor/xiaomi/aries/proprietary/lib/libmmmpo.so:system/lib/libmmmpo.so \
    vendor/xiaomi/aries/proprietary/lib/libmmmpod.so:system/lib/libmmmpod.so \
    vendor/xiaomi/aries/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/xiaomi/aries/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/xiaomi/aries/proprietary/lib/libmmQSM.so:system/lib/libmmQSM.so \
    vendor/xiaomi/aries/proprietary/lib/libmmrtpdecoder.so:system/lib/libmmrtpdecoder.so \
    vendor/xiaomi/aries/proprietary/lib/libmmrtpencoder.so:system/lib/libmmrtpencoder.so \
    vendor/xiaomi/aries/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/xiaomi/aries/proprietary/lib/libmmwfdinterface.so:system/lib/libmmwfdinterface.so \
    vendor/xiaomi/aries/proprietary/lib/libmmwfdsinkinterface.so:system/lib/libmmwfdsinkinterface.so \
    vendor/xiaomi/aries/proprietary/lib/libmmwfdsrcinterface.so:system/lib/libmmwfdsrcinterface.so \
    vendor/xiaomi/aries/proprietary/lib/libmorpho_memory_allocator.so:system/lib/libmorpho_memory_allocator.so \
    vendor/xiaomi/aries/proprietary/lib/libmorpho_panorama.so:system/lib/libmorpho_panorama.so \
    vendor/xiaomi/aries/proprietary/lib/libmp3lame.so:system/lib/libmp3lame.so \
    vendor/xiaomi/aries/proprietary/lib/libnamespaces.so:system/lib/libnamespaces.so \
    vendor/xiaomi/aries/proprietary/lib/libnap.so:system/lib/libnap.so \
    vendor/xiaomi/aries/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/xiaomi/aries/proprietary/lib/libnexcralbody_mc_jb.so:system/lib/libnexcralbody_mc_jb.so \
    vendor/xiaomi/aries/proprietary/lib/libnexeditorsdk.so:system/lib/libnexeditorsdk.so \
    vendor/xiaomi/aries/proprietary/lib/libnexralbody_audio.so:system/lib/libnexralbody_audio.so \
    vendor/xiaomi/aries/proprietary/lib/liboctvm.so:system/lib/liboctvm.so \
    vendor/xiaomi/aries/proprietary/lib/liboctvm_drv.so:system/lib/liboctvm_drv.so \
    vendor/xiaomi/aries/proprietary/lib/liboctvm_runtime.so:system/lib/liboctvm_runtime.so \
    vendor/xiaomi/aries/proprietary/lib/liboctvm_utils.so:system/lib/liboctvm_utils.so \
    vendor/xiaomi/aries/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/xiaomi/aries/proprietary/lib/liboemcrypto.so:system/lib/liboemcrypto.so \
    vendor/xiaomi/aries/proprietary/lib/libOmxAmrwbplusDec.so:system/lib/libOmxAmrwbplusDec.so \
    vendor/xiaomi/aries/proprietary/lib/libOmxMux.so:system/lib/libOmxMux.so \
    vendor/xiaomi/aries/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
    vendor/xiaomi/aries/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/xiaomi/aries/proprietary/lib/libpatcher_jni.so:system/lib/libpatcher_jni.so \
    vendor/xiaomi/aries/proprietary/lib/libPinguoImageSDK.so:system/lib/libPinguoImageSDK.so \
    vendor/xiaomi/aries/proprietary/lib/libplayer_jni.so:system/lib/libplayer_jni.so \
    vendor/xiaomi/aries/proprietary/lib/libpowerkeeper_jni.so:system/lib/libpowerkeeper_jni.so \
    vendor/xiaomi/aries/proprietary/lib/libprdrmdecrypt.so:system/lib/libprdrmdecrypt.so \
    vendor/xiaomi/aries/proprietary/lib/libprofiler_msmadc.so:system/lib/libprofiler_msmadc.so \
    vendor/xiaomi/aries/proprietary/lib/libqcci_adc.so:system/lib/libqcci_adc.so \
    vendor/xiaomi/aries/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
    vendor/xiaomi/aries/proprietary/lib/libqcomfm_jni.so:system/lib/libqcomfm_jni.so \
    vendor/xiaomi/aries/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/xiaomi/aries/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/xiaomi/aries/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/xiaomi/aries/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/xiaomi/aries/proprietary/lib/libqmi_csvt_srvc.so:system/lib/libqmi_csvt_srvc.so \
    vendor/xiaomi/aries/proprietary/lib/libqminvapi.so:system/lib/libqminvapi.so \
    vendor/xiaomi/aries/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/xiaomi/aries/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    vendor/xiaomi/aries/proprietary/lib/libQuadrangleRecognizer.so:system/lib/libQuadrangleRecognizer.so \
    vendor/xiaomi/aries/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/xiaomi/aries/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/xiaomi/aries/proprietary/lib/librmp.so:system/lib/librmp.so \
    vendor/xiaomi/aries/proprietary/lib/librtp_jni.so:system/lib/librtp_jni.so \
    vendor/xiaomi/aries/proprietary/lib/libsechook.so:system/lib/libsechook.so \
    vendor/xiaomi/aries/proprietary/lib/libsecurity_device_credential_sdk.so:system/lib/libsecurity_device_credential_sdk.so \
    vendor/xiaomi/aries/proprietary/lib/libsensor1.so:system/lib/libsensor1.so \
    vendor/xiaomi/aries/proprietary/lib/libsensor_reg.so:system/lib/libsensor_reg.so \
    vendor/xiaomi/aries/proprietary/lib/libsensor_test.so:system/lib/libsensor_test.so \
    vendor/xiaomi/aries/proprietary/lib/libsensor_user_cal.so:system/lib/libsensor_user_cal.so \
    vendor/xiaomi/aries/proprietary/lib/libsgmain.so:system/lib/libsgmain.so \
    vendor/xiaomi/aries/proprietary/lib/libsgmainso-5.1.2011.so:system/lib/libsgmainso-5.1.2011.so \
    vendor/xiaomi/aries/proprietary/lib/libshell.so:system/lib/libshell.so \
    vendor/xiaomi/aries/proprietary/lib/libshell_jni.so:system/lib/libshell_jni.so \
    vendor/xiaomi/aries/proprietary/lib/libshellservice.so:system/lib/libshellservice.so \
    vendor/xiaomi/aries/proprietary/lib/libSHIMDivxDrm.so:system/lib/libSHIMDivxDrm.so \
    vendor/xiaomi/aries/proprietary/lib/libsic_helper.so:system/lib/libsic_helper.so \
    vendor/xiaomi/aries/proprietary/lib/libsmsprotocol.so:system/lib/libsmsprotocol.so \
    vendor/xiaomi/aries/proprietary/lib/libspaces_jni.so:system/lib/libspaces_jni.so \
    vendor/xiaomi/aries/proprietary/lib/libsqlcipher_android-ss40103.so:system/lib/libsqlcipher_android-ss40103.so \
    vendor/xiaomi/aries/proprietary/lib/libsrsprocessing.so:system/lib/libsrsprocessing.so \
    vendor/xiaomi/aries/proprietary/lib/libssutil.so:system/lib/libssutil.so \
    vendor/xiaomi/aries/proprietary/lib/libsurround_proc.so:system/lib/libsurround_proc.so \
    vendor/xiaomi/aries/proprietary/lib/libtbdecode.so:system/lib/libtbdecode.so \
    vendor/xiaomi/aries/proprietary/lib/libtcp.so:system/lib/libtcp.so \
    vendor/xiaomi/aries/proprietary/lib/libthemeutils_jni.so:system/lib/libthemeutils_jni.so \
    vendor/xiaomi/aries/proprietary/lib/libthermalclient.so:system/lib/libthermalclient.so \
    vendor/xiaomi/aries/proprietary/lib/libtile2linear.so:system/lib/libtile2linear.so \
    vendor/xiaomi/aries/proprietary/lib/libTimeService.so:system/lib/libTimeService.so \
    vendor/xiaomi/aries/proprietary/lib/libtinyxml.so:system/lib/libtinyxml.so \
    vendor/xiaomi/aries/proprietary/lib/libTmsdk-2.0.8-mfr.so:system/lib/libTmsdk-2.0.8-mfr.so \
    vendor/xiaomi/aries/proprietary/lib/libTmsdk-2.0.9-mfr.so:system/lib/libTmsdk-2.0.9-mfr.so \
    vendor/xiaomi/aries/proprietary/lib/libtzplayready.so:system/lib/libtzplayready.so \
    vendor/xiaomi/aries/proprietary/lib/libual.so:system/lib/libual.so \
    vendor/xiaomi/aries/proprietary/lib/libualutil.so:system/lib/libualutil.so \
    vendor/xiaomi/aries/proprietary/lib/libunipaychsec.so:system/lib/libunipaychsec.so \
    vendor/xiaomi/aries/proprietary/lib/libvip_channel.so:system/lib/libvip_channel.so \
    vendor/xiaomi/aries/proprietary/lib/libvip_channel_iface.so:system/lib/libvip_channel_iface.so \
    vendor/xiaomi/aries/proprietary/lib/libweibosdkcore.so:system/lib/libweibosdkcore.so \
    vendor/xiaomi/aries/proprietary/lib/libwfdcommonutils.so:system/lib/libwfdcommonutils.so \
    vendor/xiaomi/aries/proprietary/lib/libwfdhdcpcp.so:system/lib/libwfdhdcpcp.so \
    vendor/xiaomi/aries/proprietary/lib/libwfdmmsink.so:system/lib/libwfdmmsink.so \
    vendor/xiaomi/aries/proprietary/lib/libwfdmmsrc.so:system/lib/libwfdmmsrc.so \
    vendor/xiaomi/aries/proprietary/lib/libwfdmmutils.so:system/lib/libwfdmmutils.so \
    vendor/xiaomi/aries/proprietary/lib/libwfdnative.so:system/lib/libwfdnative.so \
    vendor/xiaomi/aries/proprietary/lib/libwfdrtsp.so:system/lib/libwfdrtsp.so \
    vendor/xiaomi/aries/proprietary/lib/libwfdsm.so:system/lib/libwfdsm.so \
    vendor/xiaomi/aries/proprietary/lib/libwfduibcinterface.so:system/lib/libwfduibcinterface.so \
    vendor/xiaomi/aries/proprietary/lib/libwfduibcsink.so:system/lib/libwfduibcsink.so \
    vendor/xiaomi/aries/proprietary/lib/libwfduibcsinkinterface.so:system/lib/libwfduibcsinkinterface.so \
    vendor/xiaomi/aries/proprietary/lib/libwfduibcsrc.so:system/lib/libwfduibcsrc.so \
    vendor/xiaomi/aries/proprietary/lib/libwfduibcsrcinterface.so:system/lib/libwfduibcsrcinterface.so \
    vendor/xiaomi/aries/proprietary/lib/libwhetstone_jni.so:system/lib/libwhetstone_jni.so \
    vendor/xiaomi/aries/proprietary/lib/libwhetstone_sdk.so:system/lib/libwhetstone_sdk.so \
    vendor/xiaomi/aries/proprietary/lib/libwrapnexpcmcalbody.so:system/lib/libwrapnexpcmcalbody.so \
    vendor/xiaomi/aries/proprietary/lib/libxiaomimediaplayer.so:system/lib/libxiaomimediaplayer.so \
    vendor/xiaomi/aries/proprietary/lib/libxiaomiplayerwrapper.so:system/lib/libxiaomiplayerwrapper.so \
    vendor/xiaomi/aries/proprietary/lib/libxl_stat.so:system/lib/libxl_stat.so \
    vendor/xiaomi/aries/proprietary/lib/libxl_thunder_iface.so:system/lib/libxl_thunder_iface.so \
    vendor/xiaomi/aries/proprietary/lib/libxl_thunder_sdk.so:system/lib/libxl_thunder_sdk.so \
    vendor/xiaomi/aries/proprietary/lib/libxml.so:system/lib/libxml.so \

#rootdir
PRODUCT_COPY_FILES += \
    vendor/xiaomi/aries/proprietary/rootdir/chargeonlymode:root/sbin/chargeonlymode \
    vendor/xiaomi/aries/proprietary/rootdir/e2fsck_static:root/sbin/e2fsck_static \

#vendor/app
PRODUCT_COPY_FILES += \
    vendor/xiaomi/aries/proprietary/app/Ds/Ds.apk:system/app/Ds/Ds.apk \
    vendor/xiaomi/aries/proprietary/app/Ds/arm/Ds.odex:system/app/Ds/arm/Ds.odex \

#vendor/bin
PRODUCT_COPY_FILES += \
    vendor/xiaomi/aries/proprietary/vendor/bin/slim_ap_daemon:system/vendor/bin/slim_ap_daemon \

#vendor/etc
PRODUCT_COPY_FILES += \
    vendor/xiaomi/aries/proprietary/vendor/etc/dolby/ds1-default.xml:system/vendor/etc/dolby/ds1-default.xml \
    vendor/xiaomi/aries/proprietary/vendor/etc/audio_effects.conf:system/vendor/etc/audio_effects.conf \

#vendor/lib/drm
PRODUCT_COPY_FILES += \
    vendor/xiaomi/aries/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \

#vendor/lib/egl
PRODUCT_COPY_FILES += \
    vendor/xiaomi/aries/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \

#vendor/lib/hw
PRODUCT_COPY_FILES += \
    vendor/xiaomi/aries/proprietary/vendor/lib/hw/power.qcom.so:system/vendor/lib/hw/power.qcom.so \

#vendor/lib/mediadrm
PRODUCT_COPY_FILES += \
    vendor/xiaomi/aries/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \

#vendor/lib/soundfx
PRODUCT_COPY_FILES += \
    vendor/xiaomi/aries/proprietary/vendor/lib/soundfx/libswdap.so:system/vendor/lib/soundfx/libswdap.so \

#other vendor libs
PRODUCT_COPY_FILES += \
    vendor/xiaomi/aries/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libalarmservice_jni.so:system/vendor/lib/libalarmservice_jni.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libarcsoft_beauty_shot.so:system/vendor/lib/libarcsoft_beauty_shot.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libcne.so:system/vendor/lib/libcne.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libcneconn.so:system/vendor/lib/libcneconn.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libcneqmiutils.so:system/vendor/lib/libcneqmiutils.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libdpmframework.so:system/vendor/lib/libdpmframework.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libdpmnsrm.so:system/vendor/lib/libdpmnsrm.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libepdsp.so:system/vendor/lib/libepdsp.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libloc_ext.so:system/vendor/lib/libloc_ext.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libloc_xtra.so:system/vendor/lib/libloc_xtra.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libmorpho_panorama_gp.so:system/vendor/lib/libmorpho_panorama_gp.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libmsapm_jni.so:system/vendor/lib/libmsapm_jni.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libNimsWrap.so:system/vendor/lib/libNimsWrap.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libquipc_ulp_adapter.so:system/vendor/lib/libquipc_ulp_adapter.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libsregex.so:system/vendor/lib/libsregex.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libstagefright_soft_ddpdec.so:system/vendor/lib/libstagefright_soft_ddpdec.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libtar.so:system/vendor/lib/libtar.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libvendorconn.so:system/vendor/lib/libvendorconn.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libwifiscanner.so:system/vendor/lib/libwifiscanner.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libwqe.so:system/vendor/lib/libwqe.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libxt_native.so:system/vendor/lib/libxt_native.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so \
    vendor/xiaomi/aries/proprietary/vendor/lib/libxtwifi_zpp_adaptor.so:system/vendor/lib/libxtwifi_zpp_adaptor.so \

#vendor/media
PRODUCT_COPY_FILES += \
    vendor/xiaomi/aries/proprietary/vendor/media/LMspeed_508.emd:system/vendor/media/LMspeed_508.emd \
    vendor/xiaomi/aries/proprietary/vendor/media/PFFprec_600.emd:system/vendor/media/PFFprec_600.emd
